# Generated by Django 4.2.9 on 2024-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=900)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('bloodgrp', models.CharField(blank=True, max_length=2, null=True)),
                ('student_email', models.EmailField(max_length=255, unique=True)),
                ('academy_interested', models.CharField(choices=[('A', 'Apple'), ('B', 'Balls')], max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
