# Generated by Django 4.2.9 on 2024-01-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_id_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
    ]
