# Generated by Django 4.2.9 on 2024-01-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_student_id_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Phone',
            new_name='phone',
        ),
    ]
