# Generated by Django 4.2.9 on 2024-01-12 05:03

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_phone_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Country',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(help_text='Enter the date of purchase', validators=[register.models.no_future]),
        ),
    ]
