# Generated by Django 4.2.9 on 2024-01-12 05:34

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_country_student_country_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(validators=[register.models.no_future]),
        ),
    ]
