# Generated by Django 4.2.9 on 2024-01-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DOB',
            new_name='date_of_birth',
        ),
    ]
