# Generated by Django 4.2.9 on 2024-01-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_rename_dob_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
    ]
