# Generated by Django 4.2.7 on 2024-02-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0002_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'feature')},
        ),
    ]
