# Generated by Django 4.2.7 on 2024-02-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0003_alter_feature_feature_name_alter_role_role_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
    ]
