# Generated by Django 4.2.7 on 2024-02-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0004_alter_permission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'feature')},
        ),
    ]
