# Generated by Django 4.2.7 on 2024-02-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0005_remove_user_unique_id_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
