# Generated by Django 4.2.7 on 2024-02-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0005_alter_permission_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('package_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_end_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_start_date',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='id',
            new_name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_details',
        ),
        migrations.CreateModel(
            name='PackageOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classRoom.course')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classRoom.package')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classRoom.package'),
            preserve_default=False,
        ),
    ]
