# Generated by Django 5.0.2 on 2024-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0006_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='validity',
            field=models.IntegerField(default=30),
        ),
    ]
