# Generated by Django 5.0.2 on 2024-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0007_package_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='validity',
            field=models.IntegerField(),
        ),
    ]
