# Generated by Django 4.2.7 on 2024-02-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0009_user_email_user_username_alter_enrollment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
