# Generated by Django 5.0.3 on 2024-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0010_remove_chapter_id_remove_page_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userpageactivity',
            old_name='pageactivity_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
