# Generated by Django 4.2.7 on 2024-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0011_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
