# Generated by Django 4.2.7 on 2024-03-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0008_alter_package_validity'),
        ('classRoom', '0011_alter_useractivity_id'),
    ]

    operations = [
    ]
