# Generated by Django 4.2.7 on 2024-03-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0011_rename_chapter_id_chapter_id_rename_page_id_page_id_and_more'),
        ('classRoom', '0013_settings'),
    ]

    operations = [
    ]
