# Generated by Django 4.2.7 on 2024-03-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0015_alter_chapter_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classRoom.page')),
            ],
        ),
        migrations.CreateModel(
            name='ChessPuzzle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fen', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classRoom.page')),
            ],
        ),
    ]
